### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by mmikulicic** [Polymer/pwa-starter-kit#112]
Running this on macos 10.13.4:

```
$ git clone --depth 1 https://github.com/Polymer/pwa-starter-kit my-app
$ cd my-app
$ npm --version
6.0.1
$ npm install
....
$ npm test
TypeError: Cannot read property '1' of null

error: [cli.main]   cli runtime exception: TypeError: Cannot read property '1' of null
error: [cli.main]   TypeError: Cannot read property '1' of null
    at module.exports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at module.exports (/Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/promisify-node/index.js:164:10)
    at /Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:49:23
    at Generator.next (<anonymous>)
    at /Users/mkm/tmp/my-app/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:20:71
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-starter-kit@0.8.0 test:unit: `polymer test --module-resolution=node --npm`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwa-starter-kit@0.8.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mkm/.npm/_logs/2018-05-15T23_30_06_028Z-debug.log
npm ERR! Test failed.  See above for more details.
```

(FWIW, `npm run test:integration` works and the kit builds and serves just fine)

**Comment by notwaldorf** [comment]
As listed in the [prerequisites](https://github.com/Polymer/pwa-starter-kit/wiki/2.-Setup#prerequisites), we recommend node v8.x (or 9.x), but not 10.x. There is a known problem with the `polymer cli` and node version 10.

**Comment by notwaldorf** [comment]
(I'll add a note to the "known issues" that node v10 is a problem)

**Comment by ashrafhadden** [comment]
@notwaldorf Perhaps add a note about the v10 incompatibility under [Prerequisites](https://github.com/Polymer/pwa-starter-kit/wiki/2.-Setup#prerequisites) as well
