### ISSUE TITLE
macOS HS: npm run test:unit fails with "TypeError: Cannot read property '1' of null"

### ISSUE THREAD

**Issue by alexrjs** [Polymer/pwa-starter-kit#139]
Environment:
- macOS High Sierra
- node 10.3.0
- npm 6.1.0

Steps:
1) git clone https://github.com/Polymer/pwa-starter-kit pwa.demo
2) cd pwa.demo
3) npm install
[npm-list-out.txt](https://github.com/Polymer/pwa-starter-kit/files/2062854/npm-list-out.txt)
4) npm audit fix -> cause some warnings on npm install
5) npm run test:unit
```
> pwa-starter-kit@0.8.0 test:unit /Users/homeboy/Work/py/pwa.demo
> polymer test --module-resolution=node --npm


TypeError: Cannot read property '1' of null

error: [cli.main]   cli runtime exception: TypeError: Cannot read property '1' of null
error: [cli.main]   TypeError: Cannot read property '1' of null
    at module.exports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at module.exports (/Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/promisify-node/index.js:164:10)
    at /Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:49:23
    at Generator.next (<anonymous>)
    at /Users/homeboy/Work/py/pwa.demo/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:20:71
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-starter-kit@0.8.0 test:unit: `polymer test --module-resolution=node --npm`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwa-starter-kit@0.8.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/homeboy/.npm/_logs/2018-06-01T13_32_38_812Z-debug.log
```
[2018-06-01T13_32_38_812Z-debug.log](https://github.com/Polymer/pwa-starter-kit/files/2062874/2018-06-01T13_32_38_812Z-debug.log)

Can I fix this?

Thanks and Cheers,
  Alex

**Comment by notwaldorf** [comment]
Yup, this is a [known issue](https://github.com/Polymer/pwa-starter-kit/blob/master/README.md#known-issues): node 10 isn’t supported right now. If you downgrade to 9, it’ll get rid of the error. Sorry about that!
