### ISSUE TITLE
npm start crush width "write after end" error

### ISSUE THREAD

**Issue by Akiyamka** [Polymer/pwa-starter-kit#77]
Hi guys, deploy your repository, but something went wrong.

Steps:
1. clone git clone https://github.com/PolymerLabs/pwa-starter-kit "my-app"
2. cd my-app
3. npm install end with "write after end" three times
```
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
```
[Full log](https://gist.github.com/Akiyamka/4d58f2e274e5af9c1eae07fa68107132)
4. npm start
```
> pwa-starter-kit@0.8.0 start /home/cherrytea/Git/dossier-page
> polymer serve

error:   Promise rejection: Error: Property 'builds[1].js.compile' is not any of [subschema 0],[subschema 1]
error:   Error: Property 'builds[1].js.compile' is not any of [subschema 0],[subschema 1]
    at Function.validateOptions (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-project-config/lib/index.js:235:19)
    at Function.loadOptionsFromFile (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-project-config/lib/index.js:196:25)
    at new PolymerCli (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/polymer-cli.js:89:56)
    at Object.<anonymous> (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/run.js:35:17)
    at Generator.next (<anonymous>)
    at /home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/run.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/run.js:16:12)
    at __dirname (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/run.js:33:8)
    at Object.<anonymous> (/home/cherrytea/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/lib/run.js:50:4)

```
Environment:
```
node v.8.9.4
npm v.5.8.0
OS: Manjaro Linux 17.1.8 (Hakoila)
```

**Comment by TimvdLippe** [comment]
I was unable to reproduce this issue. Is this reproducing for you 100% of the time?
