### ISSUE TITLE
pnpm compatibility

### ISSUE THREAD

**Issue by lukeshiru** [Polymer/pwa-starter-kit#85]
PWA Starter Kit doesn't work with [pnpm](https://pnpm.js.org). The only way to make it work is using the discouraged option `shamefully-flatten`. This package manager is *strict*, meaning that only works if the dependency tree is well defined in `package.json` and no packages are arbitrarily accessed. If pnpm doesn't work is because there are **missing dependencies definitions** in some packages.

I encourage the Polymer team to try a clean installation of PWA Starter Kit with pnpm, and check the logged errors to track the missing packages.

Thanks!

**Comment by keanulee** [comment]
Hmm, looks like polymer-bundler is missing `babel-types` in package.json:

```
error: [cli.main]   cli runtime exception: Error: Cannot find module 'babel-types'
error: [cli.main]   Error: Cannot find module 'babel-types'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/keanulee/Code/Polymer/pwa-starter-kit/node_modules/.registry.npmjs.org/polymer-bundler/4.0.0/node_modules/polymer-bundler/lib/es6-module-bundler.js:25:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

Used here:
https://github.com/Polymer/tools/blob/9120c1d/packages/bundler/src/es6-module-bundler.ts#L15

@usergenic can we add this, and do we need to add this elsewhere?

**Comment by usergenic** [comment]
Will look at adding a static deps check to bundler.  In the meantime I'm putting together a PR and initiate release process for today.

Thanks for filing the issue, @lukeshiru!
